www-ruby/survey_app/config/routes.rb
Rails.application.routes.draw do
  get 'layouts/readme'

  resources :users
  get 'sessions/new'
  get 'users/new'

  resources :surveys do
    post 'yes'
    post 'no'
  end
  root 'home#index'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'layouts/readme'

end

www-ruby/survey_app/app/models/survey.rb
class Survey < ActiveRecord::Base

  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true,
                  length: { minimum: 5 }
  validates :question, presence: true,
                  length: { minimum: 10 }

end

www-ruby/survey_app/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
  format: {with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: {minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

www-ruby/survey_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

www-ruby/survey_app/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def readme
  end

end

www-ruby/survey_app/app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def readme
  end
end

www-ruby/survey_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
    
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

www-ruby/survey_app/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  
  before_action :logged_in_user, only: [:create, :destroy]
  
  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end
  
  def index
    @surveys = Survey.all
  end
  
  def update
  end
  
  def create
    @survey = Survey.new(survey_params)
    @survey.yes = 0
    @survey.no = 0
    
    if @survey.save
      redirect_to @survey
    else
      render 'new'
    end
  end
  
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url
  end
  
  def yes
    @survey = Survey.find(params[:survey_id])
    if(@survey.yes == nil)
      @survey.yes = 0
    else
      @survey.yes+=1
    end
    @survey.save
    redirect_to surveys_url
  end
  
  def no
    @survey = Survey.find(params[:survey_id])
    if(@survey.no == nil)
      @survey.no = 0
    else
      @survey.no+=1
    end
    @survey.save
    redirect_to surveys_url
  end
  
  
  private
  def survey_params
    params.require(:survey).permit(:title, :question)
  end
  
end

www-ruby/survey_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

# Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

www-ruby/survey_app/app/helpers/application_helper.rb
module ApplicationHelper
end

www-ruby/survey_app/app/helpers/home_helper.rb
module HomeHelper
end

www-ruby/survey_app/app/helpers/layouts_helper.rb
module LayoutsHelper
end

www-ruby/survey_app/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

www-ruby/survey_app/app/helpers/surveys_helper.rb
module SurveysHelper
end

www-ruby/survey_app/app/helpers/users_helper.rb
module UsersHelper

end

www-ruby/survey_app/app/views/home/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Survey Application!</h1>
  
  <h2>Here you can take and create surveys</h1>
<% if logged_in? %>

<h3>You are already logged in<h3>

<%= link_to "Log out", logout_path, method: "delete", class: "btn btn-lg btn-primary", id: "white_body"%>

<% else %>
<%= link_to "Sign up here", signup_path, class: "btn btn-lg btn-primary", id: "white_body" %>
<%= link_to "Login here", login_path, class: "btn btn-lg btn-default" %>
<% end %>
</div>

<p>
  This site is dedicated to those who want answers to life's greatest questions.  Anyone can sign up for free, and then can create surveys to find out what the world thinks of any given topic.  Because if the majority of the population is in favor of a certain opinion, then that opinion must be right.<br><br>
  
  Isn't it about time you started getting answers?
</p>

www-ruby/survey_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made with Ruby on Rails 
    by <a href="http://uofu-cs4540-17.cloudapp.net/">Alfred Norm Gifford</a>
    and <a href="http://uofu-cs4540-57.cloudapp.net/">Kyle Pierson</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "readme", 'layouts/readme' %></li>  
      <li><%= link_to "Ruby on Rails Tutorial", 'https://www.railstutorial.org' %></li>
    </ul>
  </nav>
</footer>

www-ruby/survey_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% link_to "survey app", root_path, id: "logo" %>
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
	<% if logged_in? %>
        <li><%= link_to "Current Surveys", controller: 'surveys' %></li>
	<li><%= link_to 'New Survey', new_survey_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account<b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
	      <%= link_to "Profile", current_user %>
	    </li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>

        <% else %>
	<li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

www-ruby/survey_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey App</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>

www-ruby/survey_app/app/views/layouts/readme.html.erb
AUTHORS: Alfred Norm Gifford and Kyle Pierson<br>
DATE:    23 April 2015<br>
PROJECT: Ruby On Rails Web Application - A Survey App<br>
VERSION: 1.0<br><br>

We made use of the Ruby on Rails Tutorial located at https://www.railstutor
ial.org/book.  Special thanks to Michael Hartl (author of the book and webp
age) for the great tutorial.<br><br>

Accessing the Website:<br>
To run the server, simply run the command:<br><br>

rails server -b 100.73.150.28 or rails server -b myuofu-cs4540 (for Kyle) or<br>
rails server -b my-uofu-cs4540 (for Norm)<br><br>

Then, point your browser toward either:<br><br>

uofu-cs4540-57.cloudapp.net:3000 (for Kyle) or<br>
uofu-cs4540-17.cloudapp.net:3000 (for Norm)<br><br>

Using the Website:<br>
The first step is to sign up as a new user.  Once you are signed up (or log
ged in), you will be able to see all current surveys as well as create your
 own.  The navbar at the top lets you navigate through these options, as we
ll as see your profile and logout.<br><br>

Shortcomings:<br>
There are a couple shortcomings to this website.  The first is that you can
 vote for a survey as many times as you want.  The second is that we are no
t displaying the users that submitted each survey.  Nevertheless, the requi
rement of being logged on as a user in order to see/submit surveys  still r
emains in tact.

www-ruby/survey_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

www-ruby/survey_app/app/views/surveys/index.html.erb
<h1>Listing Surveys</h1>

<table class='table'>
  <tr>
    <th>Title</th>
    <th>Question</th>
    <th>Answers</th>
  </tr>
  
  <% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.title %></td>
    <td><%= survey.question %></td>
    
    <td>Yes: <%= if ((survey.yes + survey.no) == 0.0)
                 0
                 else
                 (100*survey.yes/(survey.yes + survey.no)).round
                 end %>%</td>
    <td>No: <%= if ((survey.yes + survey.no) == 0.0)
                0
                else
                (100*survey.no/(survey.yes + survey.no)).round
                end %>%</td>
    
  </tr>
  <tr>
    <td><%= link_to 'Delete', survey_path(survey), class: "btn btn-danger", id: "white_body", method: 'delete', data: { confirm: 'Are you sure?' }%></td>    

    <td></td>

    <td><%= link_to 'Yes',  survey_yes_path(survey), class: "btn btn-success",  id: "white_body", method: 'post' %></td>
 
   <td><%= link_to 'No', survey_no_path(survey), class: "btn btn-primary", id: "white_body", method: 'post' %></td>
    
  </tr>
  
  <% end %>
</table>

www-ruby/survey_app/app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= form_for :survey, url: surveys_path do |f| %>
	<% if @survey.errors.any? %>
    <div id="error_explanation">
    	<h2>
        	<%= pluralize(@survey.errors.count, "error") %> prohibited
        	this article from being saved:
      	</h2>
      	<ul>
        	<% @survey.errors.full_messages.each do |msg| %>
          	<li><%= msg %></li>
        	<% end %>
      	</ul>
    </div>
  	<% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

www-ruby/survey_app/app/views/surveys/show.html.erb
<p>
<h1>Your survey has been created!</h1>

  <strong>Title:</strong>
  <%= @survey.title %>
</p>
 
<p>
  <strong>Question:</strong>
  <%= @survey.question %>
</p>

www-ruby/survey_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

www-ruby/survey_app/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'shared/error_messages', object: f.object %>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

www-ruby/survey_app/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

www-ruby/survey_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

www-ruby/survey_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h2>
	Your Account<br><br>
      </h2>
      <h1>
        <%= @user.name %><br>
	<%= @user.email %>
      </h1>
    </section>
  </aside>
</div>